services:
  - type: web
    name: mbox-web
    env: python
    buildCommand: "./build_files.sh"
    startCommand: "gunicorn commerce.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "mbox.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11"
      # Add this only if you created a PostgreSQL DB via Render
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: bidraze-db
      #     property: connectionString
